FROM rust:1.79.0
RUN cargo install sea-orm-cli
WORKDIR /service
COPY . .
RUN cargo install --path .
RUN cd migration && cargo build
RUN apt update && apt install -y netcat-traditional dnsutils
CMD nslookup test-task.czayysy80mmb.us-east-1.rds.amazonaws.com && nc -zv test-task.czayysy80mmb.us-east-1.rds.amazonaws.com 5432 && DATABASE_URL="postgres://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:5432/$DATABASE_NAME" sea-orm-cli migrate refresh && service

